# Numpy_Assignment_2::

## Question:1

In [2]:
import numpy as np

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [5]:
arr1d_1 = np.arange(10)
print("1D array: ", arr1d_1)
arr2d_1 = arr1d_1.reshape(2,5) #desired 2d array
print("1D converted to 2D array: \n", arr2d_1)

1D array:  [0 1 2 3 4 5 6 7 8 9]
1D converted to 2D array: 
 [[0 1 2 3 4]
 [5 6 7 8 9]]


## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [6]:
a_2 = np.arange(10).reshape(2,5)
print("first array \n", a_2)
b_2 = np.ones(10, dtype=int).reshape(2,5)
print("second array \n", b_2)

# Vertical stacking: Rows of second array (b_2) are appended at the end of first array (a_2) 
np.vstack((a_2, b_2)) # desired result


first array 
 [[0 1 2 3 4]
 [5 6 7 8 9]]
second array 
 [[1 1 1 1 1]
 [1 1 1 1 1]]


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [7]:
a_3 = np.arange(10).reshape(2,5)
print("first array \n", a_3)
b_3 = np.ones(10, dtype=int).reshape(2,5)
print("second array \n", b_3)

# Horizontal stacking: Append columns of 2nd array (b_3) at the end of columns of first array (a_3)
np.hstack((a_3, b_3)) # desired result

first array 
 [[0 1 2 3 4]
 [5 6 7 8 9]]
second array 
 [[1 1 1 1 1]
 [1 1 1 1 1]]


array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [74]:
arr2d_4 = np.arange(10).reshape(2,5)
print(arr2d_4) # 2-d array
flat_arr1d_4 = arr2d_4.flatten() # desired output
print("Flatten 1d array:")
print(flat_arr1d_4)


#print(arr2d_4.ndim)
#print(arr2d_4.shape)
#print(type(arr2d_4))

# multiple methods to cpnvert array of arrays into a flat 1d array
# method-1: Use of flatten() method
# flat_arr1d_4 = arr2d_4.flatten() # desired output
# print("Flatten 1d array:")
# print(flat_arr1d_4)

# method-2: Use of reshape() method
# reshape_arr1d_4 = arr2d_4.reshape(10) # need to know the original size 
# print("Reshaped 1d array:")
# print(reshape_arr1d_4)

# method-3: Use of Ravel() method
# ravel_arr1d_4 = arr2d_4.ravel()
# print("Raveled 1d array:")
# print(ravel_arr1d_4)

# method-4: Use of resize() method "Its danerous since it change the original size/shape of array"
#resized_arr1d_4 = arr2d_4.resize()
# print("\n\n\n----------")
# print("Desired Output")
#flat_arr1d_4

[[0 1 2 3 4]
 [5 6 7 8 9]]
Flatten 1d array:
[0 1 2 3 4 5 6 7 8 9]


## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [9]:
# A higher dimention array may be 2D, 3D and so on, I will consider only 2D, 3D here
arr2d_5 = np.arange(15).reshape(3,5) # 2-d array
arr3d_5 = np.arange(15).reshape(1,3,5) # 3-d array
print("\n\n\n---------2d array-------------")
print(arr2d_5) # 2-d array
print("\n\n\n---------3d array-------------")
print(arr3d_5) # 3-d array
print("\n\n\n---------2d converted to 1d array-------------")
# method-1: Using reshape()
arr1d_2d_reshape = arr2d_5.reshape(15) # 2-d converted to 1-d array by reshape() method
print(arr1d_2d_reshape)

# method-2: Using ravel()
arr1d_2d_ravled = arr2d_5.ravel() # 2-d converted to 1-d array by ravel() method
print(arr1d_2d_ravled)

# method-3: Using flatten()
arr1d_2d_flat = arr2d_5.flatten() # 2-d converted to 1-d array by flatten() method
print(arr1d_2d_flat)



print("\n\n\n---------3d converted to 1d array-------------")
# 3-d converted to 1-d array:
arr1d_3d_reshape = arr3d_5.reshape(15) # 3-d converted to 1-d array by reshape() method
arr1d_3d_ravled = arr3d_5.ravel() # 3-d converted to 1-d array by ravel() method
arr1d_3d_flat = arr3d_5.flatten() # 3-d converted to 1-d array by flatten() method
print(arr1d_3d_reshape) # 
print(arr1d_3d_ravled)
print(arr1d_3d_flat)




---------2d array-------------
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]



---------3d array-------------
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]]



---------2d converted to 1d array-------------
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]



---------3d converted to 1d array-------------
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [11]:
arr1d_6 = np.arange(15) # 1-d array
print(arr1d_6)

# converted 1d to 2d array: for desired result
arr2d_6 = arr1d_6.reshape(5,3) # desired result
arr2d_6 # desired result


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [15]:
arr5x5_7 = np.arange(25).reshape(5,5) # 5x5 array
print(arr5x5_7) # 5x5 array
print(np.square(arr5x5_7)) # square of the array
print("\n\n-----------------")
print(np.sqrt(arr5x5_7)) # square_root

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[  0   1   4   9  16]
 [ 25  36  49  64  81]
 [100 121 144 169 196]
 [225 256 289 324 361]
 [400 441 484 529 576]]


-----------------
[[0.         1.         1.41421356 1.73205081 2.        ]
 [2.23606798 2.44948974 2.64575131 2.82842712 3.        ]
 [3.16227766 3.31662479 3.46410162 3.60555128 3.74165739]
 [3.87298335 4.         4.12310563 4.24264069 4.35889894]
 [4.47213595 4.58257569 4.69041576 4.79583152 4.89897949]]


## Question:8

### Create 5x6 an array and find the mean?

In [83]:
arr5x6_8 = np.arange(30).reshape(5,6) # 5x6 array
print(arr5x6_8) # 5x6 array
np.mean(arr5x6_8) # mean of 5x6 array

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


14.5

## Question:9

### Find the standard deviation of the previous array in Q8?

In [17]:
arr5x6_8 = np.arange(30).reshape(5,6)
np.std(arr5x6_8) # standard devication of 5x6 array of Q8

8.65544144839919

## Question:10

### Find the median of the previous array in Q8?

In [18]:
arr5x6_8 = np.arange(30).reshape(5,6)
np.median(arr5x6_8) # median of 5x6 array of Q8

14.5

## Question:11

### Find the transpose of the previous array in Q8?

In [24]:
arr5x6_8 = np.arange(30).reshape(5,6)
print("Original array: \n", arr5x6_8)
print("\n\nTranspose of Original array:")
np.transpose(arr5x6_8) # transpose of 5x6 array of Q8

Original array: 
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


Transpose of Original array:


array([[ 0,  6, 12, 18, 24],
       [ 1,  7, 13, 19, 25],
       [ 2,  8, 14, 20, 26],
       [ 3,  9, 15, 21, 27],
       [ 4, 10, 16, 22, 28],
       [ 5, 11, 17, 23, 29]])

## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [36]:
arr4x4_12 = np.arange(16).reshape(4,4)
print("Original 4x4 array: \n", arr4x4_12)

arr_diagonal = np.diagonal(arr4x4_12) # diagonal elements of array:
np.sum(arr_diagonal) # sum of diagonal elements of array

#np.sum(np.diagonal(arr4x4_12)) can also be used
#np.trace(arr4x4_12) can also be used

Original 4x4 array: 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


30

## Question:13

### Find the determinant of the previous array in Q12?

In [41]:
from numpy.linalg import det
arr4x4_12 = np.arange(16).reshape(4,4)
print("Original 4x4 matrix: \n", arr4x4_12)
print("\ndeterminent of 4x4 matrix: ")
np.linalg.det(arr4x4_12)


Original 4x4 matrix: 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

determinent of 4x4 matrix: 


0.0

## Question:14

### Find the 5th and 95th percentile of an array?

In [45]:
arr_14 = np.arange(20).reshape(4,5)
print("5th percentile: ", np.percentile(arr_14, 5)) 
print("95th percentile: ", np.percentile(arr_14, 95)) 

5th percentile:  0.9500000000000001
95th percentile:  18.05


## Question:15

### How to find if a given array has any null values?

In [72]:
arr_15 = np.array([5,7,9,10,15,50,35]).astype('float')
arr_15[1] = np.nan
arr_15[5] = np.nan
print("array having null values: ", arr_15)

np.isnan(arr_15).any() # check if any array values are nul (not a number, non numeric etc) and return TRUE if found



array having null values:  [ 5. nan  9. 10. 15. nan 35.]


True