# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [4]:
import numpy as np

In [24]:
aaa = np.array([[1,2,3],[5,10,15]])
aaa.ndim
aaa.shape
#aaa.size
aaa.dtype
np.shape(aaa)

(2, 3)

2. Create a null vector of size 10 

In [10]:
# ways to create Numpy null vector:

# method-1: Using Numpy zeros() to generate null values
null_v_1 = np.zeros(10, dtype=int)
print(null_v_1)
print("Shape of null-vector:", null_v_1.shape)
print("----------------")
# method-2: Using Python list: assigning null-values maunually
null_v_2 = np.array([0,0,0,0,0,0,0,0,0,0])
print(null_v_2)
print("Shape of null-vector:", null_v_2.shape)




[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Shape of null-vector: (10,)
----------------
[0 0 0 0 0 0 0 0 0 0]
Shape of null-vector: (10,)


3. Create a vector with values ranging from 10 to 49

In [11]:
# ways to create vector:
# .1 Using Python range() function inside arrray() function
v1 = np.array(range(0,50))
print(v1)
print("Shape of vector1:", v1.shape)
print("---------------")

# 2. Using Numpy arange() function:
v2 = np.arange(50)
print("Vector v2:", v2)
print("Shape of vector2:", v2.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]
Shape of vector1: (50,)
---------------
Vector v2: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]
Shape of vector2: (50,)


4. Find the shape of previous array in question 3

In [25]:
print("Shape of vector1:", v1.shape)
print("-----")
print("Shape of vector2:", v2.shape)

Shape of vector1: (50,)
-----
Shape of vector2: (50,)


5. Print the type of the previous array in question 3

In [28]:
print("Type of vector 1:", type(v1))
print("Type of vector 2:", type(v2))

Type of vector 1: <class 'numpy.ndarray'>
Type of vector 2: <class 'numpy.ndarray'>


6. Print the numpy version and the configuration


In [13]:
#Numpy version:
print("Numpy version: ", np.__version__)

#Numpy configuration:
print(np.show_config())

Numpy version:  1.17.4
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas']
    libraries = ['openblas']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas']
    libraries = ['openblas']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas']
    libraries = ['openblas']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    library_dirs = ['C:\\projects\\numpy-wheels\\numpy\\build\\openblas']
    libraries = ['openblas']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
None


7. Print the dimension of the array in question 3


In [32]:
print("Dimension of vector 1:", v1.ndim)
print("Dimension of vector 2:", v2.ndim)

Dimension of vector 1: 1
Dimension of vector 2: 1


8. Create a boolean array with all the True values

In [15]:
arr_bool = np.ones(10, dtype=bool)
arr_bool

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

9. Create a two dimensional array




In [21]:
# method-1: passing lists inside array()
arr2d = np.array([[10, 20, 30],[5, 15, 25]])
print(arr2d)
print(arr2d.ndim)

# method-2: Using reshape() function
a2d = np.arange(10).reshape(2,5)
print(a2d)
print(a2d.ndim)

[[10 20 30]
 [ 5 15 25]]
2
[[0 1 2 3 4]
 [5 6 7 8 9]]
2


10. Create a three dimensional array



In [25]:
# method-1:
arr3d = np.array([[[1,2,3], [4,5,6], [7,8,9]]])
print(arr3d)
print(arr3d.ndim)

# method-2: Using reshape()
a3d =np.arange(25).reshape(1,5,5) 
print(a3d)
print(a3d.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
3
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]
  [20 21 22 23 24]]]
3


Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [38]:
v1 = np.arange(10)
print("OriginalVector:", v1)

# method-1: Using flip() function
rv1 = np.flip(v1, 0) # np.flip() reverse the order of vector axis=0 horizontally/row vise, axis=1 vertically/column vise
print("Reverse vector :", rv1)

# method-2: Using slicing
rv2 = v1[::-1]
print("Revserse vector 2:", rv2)




OriginalVector: [0 1 2 3 4 5 6 7 8 9]
Reverse vector : [9 8 7 6 5 4 3 2 1 0]
Revserse vector 2: [9 8 7 6 5 4 3 2 1 0]


12. Create a null vector of size 10 but the fifth value which is 1 

In [40]:
null_v = np.zeros(10,  dtype='int32')
print("Null vector of size 10: ", null_v)

# method-1:
null_v[4] = 1 #assigning 1 at 5th position:
print(null_v)

# method-2:
(np.arange(10) == 4 ).astype(int)
#np.arange(10) * 1
#null_v_alike = np.zeros.alike(10, 5)

Null vector of size 10:  [0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 1 0 0 0 0 0]


array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

13. Create a 3x3 identity matrix

In [42]:
iMat_3x3 = np.eye(3, dtype='int32')
print(iMat_3x3)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [43]:
arr = np.array([1,2,3,4,5])
# method-1: type casting/explicit conversion
m1_arr = np.array([1,2,3,4,5]).astype(float)
print("method-1:", m1_arr)

# method-2:
m2_arr = np.array([1,2,3,4,5], dtype='float32')
print("method-2:", m2_arr)

# method-3:
m3_arr = np.array([1,2,3,4,5], 'float')
print("method-3:", m3_arr)

# method-4: By changing any single value of array as floatig point
arr = np.array([1,2,3,4,5])
m4_arr = np.array([1,2,3,4,5.1])
print("method-4:", m4_arr)


method-1: [1. 2. 3. 4. 5.]
method-2: [1. 2. 3. 4. 5.]
method-3: [1. 2. 3. 4. 5.]
method-4: [1.  2.  3.  4.  5.1]


15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [43]:
# 15: Multiply arr1 with arr2:

arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]])  
arr2 = np.array([[0., 4., 1.],

           [7., 2., 12.]])
product_arr3 = arr1 * arr2
product_arr3

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [49]:
# Make an array by comparing both the arrays provided:

arr1 = np.array([[1., 2., 3.],

                [4., 5., 6.]]) 

arr2 = np.array([[0., 4., 1.],

                [7., 2., 12.]])

# method-1:
new_arr1 = arr1 == arr2 
print(new_arr1)

# method-2:
new_arr2 = arr1 > arr2
print(new_arr2)

# method-3:
new_arr3 = arr1 >= arr2
print(new_arr3)

# method-4:
new_arr4 = arr1 < arr2
print(new_arr4)

# method-5:
new_arr5 = arr1 <= arr2
print(new_arr5)

[[False False False]
 [False False False]]
[[ True False  True]
 [False  True False]]
[[ True False  True]
 [False  True False]]
[[False  True False]
 [ True False  True]]
[[False  True False]
 [ True False  True]]


17. Extract all odd numbers from arr with values(0-9)

In [94]:
# method-1: code is not working with this way, don;t know why?
arr = np.arange(10)
print("array(0-9): ", arr)
arr[arr % 2 == 1]
print(arr)
print("------------------")
# method-2:
a1 = np.array([0,1,2,3,4,5,6,7,8,9])
print("Array(0-9): ", a1)
print("Extracted odd values:", a1[a1 % 2 == 1])

# method-3:
a2 = np.array(range(10))
print("Array(0-9):", a2)
print("Extracted odd values:", a2[a2 % 2 == 1])

array(0-9):  [0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
------------------
Array(0-9):  [0 1 2 3 4 5 6 7 8 9]
Extracted odd values: [1 3 5 7 9]
Array(0-9): [0 1 2 3 4 5 6 7 8 9]
Extracted odd values: [1 3 5 7 9]


18. Replace all odd numbers to -1 from previous array

In [98]:
a18 = np.array([0,1,2,3,4,5,6,7,8,9])
print("Array(0-9): ", a18)
a18[a18 % 2 == 1] = -1
a18
print("Odd values replaced with -1:", a18)

Array(0-9):  [0 1 2 3 4 5 6 7 8 9]
Odd values replaced with -1: [ 0 -1  2 -1  4 -1  6 -1  8 -1]


19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [121]:
arr19 = np.arange(10)
print(arr19)
# method-1: By slicing
arr19[5:9]=12
print(arr19)
print("-----------------")
# method-2: "bare slice"
arr19_slice = arr19[0:2] # can use arr19[5:8] but changed index position to show change in arr19 
print(arr19_slice)
arr19_slice[:] = 12
print(arr19)

[0 1 2 3 4 5 6 7 8 9]
[ 0  1  2  3  4 12 12 12 12  9]
-----------------
[0 1]
[12 12  2  3  4 12 12 12 12  9]


20. Create a 2d array with 1 on the border and 0 inside

In [133]:
a2d20 = np.ones((5,5), dtype=int)
print("Original 2d array:")
print(a2d20)

a2d20[1:-1,1: -1] = 0
print("1 on the border and 0 inside: ")
print(a2d20)

Original 2d array:
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
1 on the border and 0 inside: 
[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [147]:
arr2d_21 = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
print(arr2d_21)

# method-1:
arr2d_21[1][1] = 12
print("method-1:", arr2d_21)

# method-2:
arr2d_21[1,1] = 12
print("method-2:", arr2d_21)



[[1 2 3]
 [4 5 6]
 [7 8 9]]
method-1: [[ 1  2  3]
 [ 4 12  6]
 [ 7  8  9]]
method-2: [[ 1  2  3]
 [ 4 12  6]
 [ 7  8  9]]


22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [153]:
arr3d_22 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr3d_22)
arr3d_22[0][0] = 64 # arr3d_22[0,0] = 64 1st array
arr3d_22

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


array([[[64, 64, 64],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [169]:
arr2d_23 = np.arange(10).reshape(5,2)
print(arr2d_23)
arr1d_23 = arr2d_23[0:1,0:]
print("1st 1d extracted: ", arr1d_23)
print("-------------")

arr2d23 = np.arange(10).reshape(2,5)
print(arr2d23)
arr1d23 = arr2d23[0:1,0:]
print("1st 1d ectracted: ", arr1d23)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
1st 1d extracted:  [[0 1]]
-------------
[[0 1 2 3 4]
 [5 6 7 8 9]]
1st 1d ectracted:  [[0 1 2 3 4]]


24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [186]:
arr2d_24 = np.arange(10).reshape(2,5)
print(arr2d_24)
value_2ndarr = arr2d_24[1,1]
print(value_2ndarr)

value_2ndarr = arr2d_24[1][1]
print(value_2ndarr)

value_2ndarr = arr2d_24[1:2,1:2] #slice out 2nd value of 2nd 1d array
print(value_2ndarr)

[[0 1 2 3 4]
 [5 6 7 8 9]]
6
6
[[6]]


25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [189]:
arr2d_25 = np.arange(10).reshape(2,5)
print(arr2d_25)
arr2d_25[0:2,2:3]

[[0 1 2 3 4]
 [5 6 7 8 9]]


array([[2],
       [7]])

26. Create a 10x10 array with random values and find the minimum and maximum values

In [203]:
arr_rand_26 = np.random.random((10,10))
print("Orignial 10x10 Array with random values: ", arr_rand_26)
print(arr_rand_26.shape)

arr_rand_26_min = arr_rand_26.min()
print("min of array: ", arr_rand_26_min )

arr_rand_26_max = arr_rand_26.max()
print("max of array: ", arr_rand_26_max )



Orignial 10x10 Array with random values:  [[8.02967024e-01 9.89930368e-01 2.93932144e-01 1.76161995e-01
  8.98025484e-01 4.82108673e-02 6.85100820e-01 8.15450264e-01
  5.44609974e-01 3.55304188e-01]
 [7.14456510e-01 3.86881547e-01 8.32230451e-01 1.78037974e-02
  5.06052535e-01 5.12124816e-01 4.86723448e-01 3.20575452e-01
  2.93963310e-01 5.61142669e-01]
 [8.33538887e-01 6.24444787e-01 6.50273150e-01 7.52505651e-01
  4.84454588e-01 7.26564924e-01 7.01915693e-01 6.15334995e-01
  9.38227715e-01 5.04913742e-01]
 [3.59155875e-01 4.97877803e-01 2.98843346e-03 2.38849936e-01
  4.56191080e-01 4.12005537e-01 1.02684225e-02 6.07695746e-01
  2.92711189e-01 6.66821144e-01]
 [6.26003037e-01 3.68256060e-01 2.22863762e-01 1.28365464e-01
  8.59910334e-03 7.22544226e-01 7.56314532e-01 8.58942808e-01
  5.27729208e-01 1.89702693e-01]
 [1.23174466e-01 6.00836372e-01 9.23511140e-01 5.86544030e-01
  8.36358014e-01 9.11310588e-01 1.14160761e-01 5.88608371e-01
  2.73866201e-01 9.53451922e-01]
 [9.81247406e-02

27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [210]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
print("Original arrays: ", a, ' ', b)

c = np.intersect1d(a,b)
print("Common items between a and b: ", c)

Original arrays:  [1 2 3 2 3 4 3 4 5 6]   [ 7  2 10  2  7  4  9  4  9  8]
Common items between a and b:  [2 4]


28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [223]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
print("Original arrays: ", a, ' ', b)
c = np.searchsorted(a, np.intersect1d(a, b)) #np.searchsorted(b, np.intersect1d(a, b))
print("Indices of common values wrt a: ", c) #repeated value with 1st ocurance indices

Original arrays:  [1 2 3 2 3 4 3 4 5 6]   [ 7  2 10  2  7  4  9  4  9  8]
Indices of common values wrt a:  [0 2]


29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [232]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
data[names != 'Will'] 

#data.shape

array([[ 0.36339201,  0.10818966, -1.34056878,  1.20437067],
       [ 0.67104998,  1.55936738, -0.51723477,  0.34562584],
       [-0.6450226 ,  0.49488151,  0.85175137, -0.38833395],
       [-0.59749386,  0.32690987,  0.66328302, -0.6321852 ],
       [ 2.25966935, -0.36151693, -2.21887735,  0.56278518]])

30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [235]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
data[(names != 'Will') | (names != 'Joe')]

array([[ 0.43239631,  1.35900846, -1.62087042,  0.32674555],
       [ 0.06084357, -0.43849968,  0.3979831 , -1.14336322],
       [ 1.62742342,  1.46523033, -1.47144254,  0.28260106],
       [-1.35179465,  0.04699355, -1.79201796, -0.41857531],
       [-0.43189701,  1.3429804 , -0.43483717, -1.34215536],
       [ 0.50018011, -0.97570498,  1.12580595, -1.33570485],
       [ 0.01780515, -0.02118342, -0.13044697, -0.44948553]])

Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [239]:
arr2d_31 = np.array(range(1,16)).reshape(5,3)
print(arr2d_31)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [242]:
arr_2x2x4_32 = np.array(range(1,17)).reshape(2,2,4)
arr_2x2x4_32

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

33. Swap axes of the array you created in Question 32

In [249]:
print(np.swapaxes(arr_2x2x4_32,0,1)) # swap axes 0, 1
print(np.swapaxes(arr_2x2x4_32,0,2)) # swap axes 0, 2
print(np.swapaxes(arr_2x2x4_32,1,2)) # swap axes 1, 2
print(np.swapaxes(arr_2x2x4_32,2,1)) # swap axes 2, 1

[[[ 1  2  3  4]
  [ 9 10 11 12]]

 [[ 5  6  7  8]
  [13 14 15 16]]]
[[[ 1  9]
  [ 5 13]]

 [[ 2 10]
  [ 6 14]]

 [[ 3 11]
  [ 7 15]]

 [[ 4 12]
  [ 8 16]]]
[[[ 1  5]
  [ 2  6]
  [ 3  7]
  [ 4  8]]

 [[ 9 13]
  [10 14]
  [11 15]
  [12 16]]]
[[[ 1  5]
  [ 2  6]
  [ 3  7]
  [ 4  8]]

 [[ 9 13]
  [10 14]
  [11 15]
  [12 16]]]


34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [267]:
# create an array of size 10
arr_34 = np.random.randn(10)
print("Original array: ", arr_34)

# find square root of every element in array
sqrt_arr_34 = np.sqrt(arr_34) # arr_34 ** 0.5
print("Square root of array elements: ", sqrt_arr_34)

arr_34[arr_34 < 0.5] = 0
print("Replace with 0 if <0.5 ", arr_34)

Original array:  [-0.24280277  0.46449371 -0.17644683 -0.68495714  0.81083044 -1.22611175
 -0.24956811 -0.4330389   1.36285348 -0.0442524 ]
Square root of array elements:  [       nan 0.68153776        nan        nan 0.90046124        nan
        nan        nan 1.16741316        nan]
Replace with 0 if <0.5  [0.         0.         0.         0.         0.81083044 0.
 0.         0.         1.36285348 0.        ]


c:\users\nasir\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:6: RuntimeWarning: invalid value encountered in sqrt
  


35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [283]:
a_35 = np.random.randint(0,13, size=12)
b_35 = np.random.randint(0,13, size=12)
print("Original random arrays of range 12: ", a_35, ' ', b_35)

maxValues = np.maximum.reduce([a_35, b_35])   
print("Element-wise maximum values between a_35 and b_35 arrays: ", maxValues)

Original random arrays of range 12:  [ 2  0  5  2  2 11  2  9  6  7  5  1]   [ 4  6  1 10  7  3 11  9  8  5  9  9]
Element-wise maximum values between a_35 and b_35 arrays:  [ 4  6  5 10  7 11 11  9  8  7  9  9]


36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [288]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
uniqueNames = np.unique(names) #method-1 it finds unique names in sorted order
print(uniqueNames)
sorted(set(uniqueNames)) # alternative method

['Bob' 'Joe' 'Will']


['Bob', 'Joe', 'Will']

37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [297]:
a = np.array([1,2,3,4,5]) 
b = np.array([5,6,7,8,9])
print("Original arrays: ", a, ' ', b)

common = np.intersect1d(a,b)
print("Elements of array a present in b: ", common)
remove_comm = np.setdiff1d(a,b) # remove all elements of a present in b
print("Array a after removing common elements with b: ", remove_comm)

Original arrays:  [1 2 3 4 5]   [5 6 7 8 9]
Elements of array a present in b:  [5]
Array a after removing common elements with b:  [1 2 3 4]


38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [318]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]]) 
print("Original array: \n", sampleArray)

sampleArray[0:,1:2] = 10 # column 2 assigned values 10
#newColumn = np.array([[10,10,10]])
print("Values of new column: ", newColumn)
sampleArray

Original array: 
 [[34 43 73]
 [82 22 12]
 [53 94 66]]
Values of new column:  [[10 10 10]]


array([[34, 10, 73],
       [82, 10, 12],
       [53, 10, 66]])

39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [321]:
x = np.array([[1., 2., 3.], [4., 5., 6.]]) 
y = np.array([[6., 23.], [-1, 7], [8, 9]])
print("Dot product of above two matices:")
np.dot(x,y)

Dot product of above two matices:


array([[ 28.,  64.],
       [ 67., 181.]])

40. Generate a matrix of 20 random values and find its cumulative sum

In [341]:
# method-1:
randMat_40 = np.random.random(20).reshape(2,10) 
print(randMat_40.cumsum()) # Cummulative Sum
#print(np.cumsum(randMat_40))

# method-2:
arr = np.random.randn(4,5) # matrix of 20 random values
arr.cumsum() # Cummulative Sum

[ 0.93801151  1.0416107   1.21089078  1.29318252  1.39271329  2.05705971
  3.0098601   3.20902121  3.8806763   4.26402308  5.08281679  6.03090596
  6.69216804  6.81169005  6.97727748  7.96981803  8.93497708  9.66899529
 10.39498995 10.52525377]


array([0.63482066, 2.44787658, 1.68908447, 3.08718535, 3.76734664,
       5.18785956, 5.17877671, 3.04173945, 2.93479648, 3.83534111,
       3.34673358, 3.62237876, 2.83661573, 2.61186715, 2.47997118,
       1.99276295, 3.64014566, 3.5973378 , 4.01234814, 5.41389981])